include(CheckCXXCompilerFlag)
include(CheckCXXSourceCompiles)
include(CheckIPOSupported)

function(_ducc0_dispatch_profile profile key level flag)
  if(profile STREQUAL "x86-64")
    set(_key x86_64)
    set(_level 1)
    if(MSVC)
      set(_flag "")
    else()
      set(_flag "-march=x86-64")
    endif()
  elseif(profile STREQUAL "x86-64-v2")
    set(_key x86_64_v2)
    set(_level 2)
    if(MSVC)
      set(_flag "/arch:SSE4.2")
    else()
      set(_flag "-march=x86-64-v2")
    endif()
  elseif(profile STREQUAL "x86-64-v3")
    set(_key x86_64_v3)
    set(_level 3)
    if(MSVC)
      set(_flag "/arch:AVX2")
    else()
      set(_flag "-march=x86-64-v3")
    endif()
  elseif(profile STREQUAL "x86-64-v4")
    set(_key x86_64_v4)
    set(_level 4)
    if(MSVC)
      set(_flag "/arch:AVX512")
    else()
      set(_flag "-march=x86-64-v4")
    endif()
  else()
    message(FATAL_ERROR "Unknown DUCC0 x86-64 dispatch profile: ${profile}")
  endif()
  set(${key} "${_key}" PARENT_SCOPE)
  set(${level} "${_level}" PARENT_SCOPE)
  set(${flag} "${_flag}" PARENT_SCOPE)
endfunction()

function(ducc0_configure_cpu_dispatch)
  string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" _processor)
  if(NOT _processor MATCHES "^(x86_64|amd64|x64)$" OR
     CMAKE_SYSTEM_NAME STREQUAL "Emscripten")
    message(FATAL_ERROR
      "DUCC0_OPTIMIZATION=dispatch requires an x86-64 target; "
      "got ${CMAKE_SYSTEM_PROCESSOR} (${CMAKE_SYSTEM_NAME})")
  endif()

  # Global ISA or LTO flags would also affect the common and profile objects.
  get_cmake_property(_variables VARIABLES)
  set(_flag_text "")
  foreach(_var IN LISTS _variables)
    if(_var MATCHES "^CMAKE_(CXX|EXE_LINKER|SHARED_LINKER|MODULE_LINKER)_FLAGS($|_)")
      string(APPEND _flag_text " ${${_var}}")
    endif()
  endforeach()
  foreach(_env IN ITEMS DUCC0_CFLAGS DUCC0_FLAGS DUCC0_LFLAGS)
    string(APPEND _flag_text " $ENV{${_env}}")
  endforeach()
  string(TOLOWER "${_flag_text}" _lower_flags)
  if(_lower_flags MATCHES "(^|[ \t])(-flto([^ \t]*)?|/gl)([ \t]|$)")
    message(FATAL_ERROR
      "Global LTO flags are not allowed in dispatch mode; "
      "CMake enables IPO only for common DUCC0 code")
  endif()
  string(REGEX REPLACE "(^|[ \t])-march=x86-64([ \t]|$)" " " _isa_flags
    "${_lower_flags}")
  if(_isa_flags MATCHES
      "(^|[ \t])(-march=[^ \t]+|-mcpu=[^ \t]+|-m(avx[^ \t]*|sse3|ssse3|sse4[^ \t]*|popcnt|cx16|lahf[^ \t]*|fma|bmi[^ \t]*|lzcnt|f16c|movbe)|/arch:(avx[^ \t]*|sse[34][^ \t]*))([ \t]|$)")
    message(FATAL_ERROR
      "Global ISA flags are not allowed in dispatch mode; "
      "set the target through DUCC0_DISPATCH_PROFILES instead")
  endif()

  if(DEFINED ENV{DUCC0_DISPATCH_PROFILES})
    set(DUCC0_DISPATCH_PROFILES "$ENV{DUCC0_DISPATCH_PROFILES}" CACHE STRING
      "x86-64 profiles to compile in dispatch mode (add x86-64-v2 for developer tests)" FORCE)
  else()
    set(DUCC0_DISPATCH_PROFILES "x86-64;x86-64-v3;x86-64-v4" CACHE STRING
      "x86-64 profiles to compile in dispatch mode (add x86-64-v2 for developer tests)")
  endif()

  set(_all_profiles x86-64 x86-64-v2 x86-64-v3 x86-64-v4)
  set(_requested)
  set(_enabled)
  foreach(_profile IN LISTS DUCC0_DISPATCH_PROFILES)
    if(NOT _profile IN_LIST _all_profiles)
      message(FATAL_ERROR "Unknown DUCC0 dispatch profile: ${_profile}")
    endif()
    if(_profile IN_LIST _requested)
      message(FATAL_ERROR "Duplicate DUCC0 dispatch profile: ${_profile}")
    endif()
    list(APPEND _requested "${_profile}")
    _ducc0_dispatch_profile("${_profile}" _key _level _flag)
    if(_flag STREQUAL "")
      check_cxx_source_compiles("int main() { return 0; }"
        DUCC0_DISPATCH_COMPILER_${_key})
    else()
      check_cxx_compiler_flag("${_flag}" DUCC0_DISPATCH_COMPILER_${_key})
    endif()
    if(DUCC0_DISPATCH_COMPILER_${_key})
      list(APPEND _enabled "${_profile}")
      set(DUCC0_DISPATCH_FLAG_${_key} "${_flag}" PARENT_SCOPE)
    elseif(_level EQUAL 1)
      message(FATAL_ERROR "Compiler cannot build the x86-64 baseline profile")
    else()
      message(STATUS "Omitting ${_profile}: compiler profile check failed")
    endif()
  endforeach()
  if(NOT "x86-64" IN_LIST _enabled)
    message(FATAL_ERROR "DUCC0_DISPATCH_PROFILES must include x86-64")
  endif()

  option(DUCC0_DISPATCH_COMMON_IPO
    "Enable IPO/LTO for common code in x86-64 dispatch builds" ON)
  set(DUCC0_DISPATCH_PROFILES "${_enabled}" PARENT_SCOPE)
endfunction()

function(ducc0_finalize_cpu_dispatch target)
  target_compile_definitions(${target} PRIVATE DUCC0_CPU_DISPATCH=1)
  if(NOT MSVC)
    target_compile_definitions(${target} PRIVATE DUCC0_X86_64_LEVEL=1)
  endif()

  foreach(_profile IN LISTS DUCC0_DISPATCH_PROFILES)
    _ducc0_dispatch_profile("${_profile}" _key _level _flag)
    if(_level GREATER 1)
      string(TOUPPER "${_key}" _key_upper)
      target_compile_definitions(${target} PRIVATE
        DUCC0_DISPATCH_FFT_HAS_${_key_upper}=1)
    endif()
  endforeach()

  get_target_property(_common_options ${target} COMPILE_OPTIONS)
  get_target_property(_common_definitions ${target} COMPILE_DEFINITIONS)
  if(_common_options MATCHES "-NOTFOUND$")
    set(_common_options)
  endif()
  if(_common_definitions MATCHES "-NOTFOUND$")
    set(_common_definitions)
  endif()
  set(_profile_definitions)
  foreach(_definition IN LISTS _common_definitions)
    if(NOT _definition MATCHES "^DUCC0_(CPU_DISPATCH|X86_64_LEVEL|DISPATCH_)")
      list(APPEND _profile_definitions "${_definition}")
    endif()
  endforeach()

  foreach(_profile IN LISTS DUCC0_DISPATCH_PROFILES)
    _ducc0_dispatch_profile("${_profile}" _key _level _flag)
    set(_object "ducc0_dispatch_${_key}")
    add_library(${_object} OBJECT src/ducc0/fft/fft_dispatch_target.cc)
    target_include_directories(${_object} PRIVATE "${CMAKE_SOURCE_DIR}/src")
    target_compile_features(${_object} PRIVATE cxx_std_17)
    target_compile_definitions(${_object} PRIVATE ${_profile_definitions}
      DUCC0_DISPATCH_TARGET=1 DUCC0_X86_64_LEVEL=${_level})
    target_compile_options(${_object} PRIVATE ${_common_options})
    if(NOT _flag STREQUAL "")
      target_compile_options(${_object} PRIVATE "${_flag}")
    endif()
    set_target_properties(${_object} PROPERTIES
      POSITION_INDEPENDENT_CODE ON
      INTERPROCEDURAL_OPTIMIZATION FALSE
      CXX_VISIBILITY_PRESET hidden
      VISIBILITY_INLINES_HIDDEN ON)
    target_sources(${target} PRIVATE $<TARGET_OBJECTS:${_object}>)
  endforeach()

  if(DUCC0_DISPATCH_COMMON_IPO)
    check_ipo_supported(RESULT _ipo_supported OUTPUT _ipo_message LANGUAGES CXX)
  else()
    set(_ipo_supported FALSE)
  endif()
  set_property(TARGET ${target} PROPERTY
    INTERPROCEDURAL_OPTIMIZATION ${_ipo_supported})

endfunction()
